version: "3"
services:
  fess01:
    image: codelibs/fess:13.6.1
    container_name: fess01
    ports:
      - "8080:8080"
    depends_on:
      - es01
      - es02
    environment:
      - RUN_ELASTICSEARCH=false
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
    networks:
      - esnet

  es01:
    image: codelibs/fess-elasticsearch:7.6.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esdictionary01:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - esnet

  es02:
    image: codelibs/fess-elasticsearch:7.6.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - esdictionary02:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9201:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    depends_on:
      - es01
      - es02
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdictionary01:
    driver: local
  esdata02:
    driver: local
  esdictionary02:
    driver: local

networks:
  esnet:
    driver: bridge
